language: java

jdk:
  - openjdk17

sudo: false


notifications:
  email:
    recipients:
      - e.g.zakharov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always